#!/usr/bin/env bash

prj_root=`dirname $(realpath "$0")`/..
tgt_dir=$prj_root/target
rel_dir=$tgt_dir/release
rel_bin_dir=$rel_dir/bin
dbg_dir=$tgt_dir/debug
dbg_bin_dir=$tgt_dir/debug/bin

hello_dir=$prj_root/hello_compartment
hello_exe=$hello_dir/hello_compartment

life_dir=$prj_root/life
life_exe=$rel_bin_dir/life
life_dbg=$dbg_bin_dir/life

report_dir=$prj_root/report

# cmd="./life -c 100"
# cmd="./life -s 3 -c 100 -i 011001010"
args="-s 20 -c 100 -i 011001010110101111011001010110101111010111101010101111100110111"

# clear & reset report directory
cd $prj_root
rm -rf $report_dir
sudo -u andrew mkdir -p $report_dir

# build hello_compartment & run it
echo "Building libcompart..."
echo ""
cd $prj_root/libcompart
sudo -u andrew make clean
sudo -u andrew make
echo "...and hello_compartment..."
cd $hello_dir
sudo -u andrew make clean
sudo -u andrew make > $report_dir/a.out 2> $report_dir/a.err
echo ""
echo "done."
echo ""
echo ""
echo "Running hello_compartment..."
# running $hello_exe requires elevated privileges; if this script is not run as
# sudo, it will fail
$hello_exe
echo ""
echo "done."
echo ""
echo ""

# build
echo "Building life binaries..."
echo ""
cd $life_dir
sudo -u andrew make clean
sudo -u andrew make life > $report_dir/b.out 2> $report_dir/b.err
sudo -u andrew make DBG=true life
echo ""
echo "done."
echo ""

# run tests
echo "Measuring life runtime..."
echo ""
touch $report_dir/c.out
{ sudo -u andrew time $life_exe $args; } > $report_dir/c.out 2> $report_dir/c.err
echo ""
echo "done."
echo ""
echo ""
echo "Checking life for memory leaks..."
echo ""
sudo -u andrew valgrind $life_exe $args > $report_dir/d.out 2> $report_dir/d.err
echo ""
echo "done."
echo ""
echo ""
echo "Profiling life..."
echo ""
cd $dbg_bin_dir
sudo -u andrew $life_dbg $args
sudo -u andrew gprof $life_dbg $dbg_bin_dir/gmon.out > $report_dir/e.out 2> $report_dir/e.err
echo ""
echo "done."
echo ""
echo ""
