#!/usr/bin/env bash

prj_root=`dirname $(realpath "$0")`/..
tgt_dir=$prj_root/target

hello_dir=$prj_root/hello_compartment
hello_exe=$hello_dir/hello_compartment

life_tgt_dir=$tgt_dir/life
life_rel_dir=$life_tgt_dir/release
life_rel_bin_dir=$rel_dir/bin
life_dbg_dir=$tgt_dir/debug
life_dbg_bin_dir=$life_dbg_dir/bin

life_dir=$prj_root/life
life_exe=$life_rel_bin_dir/life
life_dbg=$life_dbg_bin_dir/life

part_tgt_dir=$tgt_dir/part
part_rel_dir=$part_tgt_dir/release
part_rel_bin_dir=$rel_dir/bin
part_dbg_dir=$part_tgt_dir/debug
part_dbg_bin_dir=$part_dbg_dir/bin

part_dir=$prj_root/part
part_exe=$part_rel_bin_dir/partitioned_life
part_dbg=$part_dbg_bin_dir/partitioned_life

report_dir=$prj_root/report

# cmd="./life -c 100"
# cmd="./life -s 3 -c 100 -i 011001010"
args="-s 20 -c 100 -i 011001010110101111011001010110101111010111101010101111100110111"

# clear & reset report directory
cd $prj_root
rm -rf $report_dir
sudo -u andrew mkdir -p $report_dir

# build hello_compartment & run it
echo "Building libcompart..."
echo ""
cd $prj_root/libcompart
sudo -u andrew make clean
sudo -u andrew make
echo "...and hello_compartment..."
cd $hello_dir
sudo -u andrew make clean
sudo -u andrew make > $report_dir/a.out 2> $report_dir/a.err
echo ""
echo "done."
echo ""
echo ""
echo "Running hello_compartment..."
# running $hello_exe requires elevated privileges; if this script is not run as
# sudo, it will fail
$hello_exe
echo ""
echo "done."
echo ""
echo ""

# build
echo "Building life binaries..."
echo ""
cd $life_dir
sudo -u andrew make clean
sudo -u andrew make life > $report_dir/b.out 2> $report_dir/b.err
sudo -u andrew make DBG=true life
echo ""
echo "done."
echo ""

# run tests
echo "Measuring life runtime..."
echo ""
touch $report_dir/c.out
{ sudo -u andrew time $life_exe $args; } > $report_dir/c.out 2> $report_dir/c.err
echo ""
echo "done."
echo ""
echo ""
echo "Checking life for memory leaks..."
echo ""
sudo -u andrew valgrind $life_exe $args > $report_dir/d.out 2> $report_dir/d.err
echo ""
echo "done."
echo ""
echo ""
echo "Profiling life..."
echo ""
cd $dbg_bin_dir
sudo -u andrew $life_dbg $args
sudo -u andrew gprof $life_dbg $life_dbg_bin_dir/gmon.out > $report_dir/e.out 2> $report_dir/e.err
echo ""
echo "done."
echo ""
echo ""

# build
echo "Building partitioned_life binaries..."
echo ""
cd $part_dir
touch $report_dir/f.out
sudo -u andrew make clean
sudo -u andrew make part > $report_dir/f.out 2> $report_dir/f.err
sudo -u andrew make PRF=true part
echo ""
echo "done."
echo ""

# run tests
echo "Measuring partitioned_life runtime..."
echo ""
touch $report_dir/g.out
{ sudo -u andrew time $part_exe $args; } > $report_dir/g.out 2> $report_dir/g.err
echo ""
echo "done."
echo ""
echo ""
echo "Checking part for memory leaks..."
echo ""
touch $report_dir/h.out
sudo -u andrew valgrind $part_exe $args > $report_dir/h.out 2> $report_dir/h.err
echo ""
echo "done."
echo ""
echo ""
echo "Profiling part..."
echo ""
cd $dbg_bin_dir
touch $report_dir/i.out
$part_dbg $args
sudo -u andrew gprof $part_dbg $part_dbg_bin_dir/gmon.out > $report_dir/i.out 2> $report_dir/i.err
echo ""
echo "done."
echo ""
echo ""
