#!/usr/bin/env bash

prj_root=`dirname $(realpath "$0")`/..
tgt_dir=$prj_root/target/part
rel_dir=$tgt_dir/release
rel_bin_dir=$rel_dir/bin
dbg_dir=$tgt_dir/debug
dbg_bin_dir=$dbg_dir/bin

part_dir=$prj_root/part
part_exe=$rel_bin_dir/partitioned_life
part_dbg=$dbg_bin_dir/partitioned_life
part_exe=$rel_bin_dir/partitioned_life

report_dir=$prj_root/report

args=" -s 3 -c 5 -i 011110010"
 
# args="-s 20 -c 100 -i 011001010110101111011001010110101111010111101010101111100110111"

# build
echo "Building part binaries..."
echo ""
cd $part_dir
sudo -u andrew make DBG=true part \
    && echo "running command: $part_dbg $args" \
    && $part_dbg $args
echo ""
echo "done."
echo ""
